version: "3.8"

services:
  redroid:
    image: redroid/redroid:11.0.0-latest
    container_name: android-redroid
    privileged: true
    ports:
      - "5555:5555"   # ADB port
    environment:
      - DISPLAY=:0
    volumes:
      - /dev/kvm:/dev/kvm
      - /dev/video10:/dev/video10
      - redroid_data:/data
    networks:
      - redroid-network

  websocket:
    build: ../ws-server
    container_name: redroid-controller
    privileged: true
    ports:
      - "3000:3000"
    environment:
      - REDROID_HOST=android-redroid
      - REDROID_PORT=5555
    volumes:
      - /tmp:/tmp
    depends_on:
      - redroid
    networks:
      - redroid-network

  frontend:
    build: ../frontend
    container_name: redroid-frontend
    ports:
      - "8050:80"
    depends_on:
      - websocket
    networks:
      - redroid-network

  # New service for Redroid display using ADB screenshots
  redroid-display:
    image: ubuntu:20.04
    container_name: redroid-display
    privileged: true
    ports:
      - "6080:6080"
    environment:
      - DISPLAY=:0
    volumes:
      - /dev/kvm:/dev/kvm
    depends_on:
      - redroid
    networks:
      - redroid-network
    command: >
      /bin/bash -c "
        apt-get update && apt-get install -y wget curl xvfb x11vnc novnc websockify python3 python3-pip &&
        # Install ADB
        apt-get install -y android-tools-adb &&
        pip3 install flask flask-cors &&
        mkdir -p /app &&
        cd /app &&
        echo 'import os
import time
import subprocess
import threading
from flask import Flask, Response, render_template_string
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

HTML_TEMPLATE = \"\"\"
<!DOCTYPE html>
<html>
<head>
    <title>Redroid Display</title>
    <style>
        body { margin: 0; padding: 20px; font-family: Arial, sans-serif; }
        .container { max-width: 1200px; margin: 0 auto; }
        .status { padding: 10px; margin: 10px 0; border-radius: 5px; }
        .success { background: #d4edda; color: #155724; }
        .error { background: #f8d7da; color: #721c24; }
        .screenshot { max-width: 100%; border: 1px solid #ddd; border-radius: 5px; }
        .controls { margin: 20px 0; }
        button { padding: 10px 20px; margin: 5px; border: none; border-radius: 5px; cursor: pointer; }
        .primary { background: #007bff; color: white; }
        .secondary { background: #6c757d; color: white; }
        .auto-refresh { background: #28a745; color: white; }
    </style>
</head>
<body>
    <div class=\"container\">
        <h1>Redroid Android Display</h1>
        <div id=\"status\" class=\"status\">Checking Redroid status...</div>
        <div class=\"controls\">
            <button class=\"primary\" onclick=\"takeScreenshot()\">Take Screenshot</button>
            <button class=\"secondary\" onclick=\"refreshStatus()\">Refresh Status</button>
            <button class=\"auto-refresh\" onclick=\"toggleAutoRefresh()\">Start Auto Refresh</button>
        </div>
        <div id=\"screenshot-container\"></div>
    </div>
    <script>
        let autoRefreshInterval = null;
        
        function takeScreenshot() {
            fetch('/screenshot')
                .then(response => response.blob())
                .then(blob => {
                    const url = URL.createObjectURL(blob);
                    const img = document.createElement('img');
                    img.src = url;
                    img.className = 'screenshot';
                    const container = document.getElementById('screenshot-container');
                    container.innerHTML = '';
                    container.appendChild(img);
                })
                .catch(error => {
                    console.error('Error:', error);
                    document.getElementById('status').innerHTML = '<div class=\"status error\">Error taking screenshot</div>';
                });
        }
        
        function refreshStatus() {
            fetch('/status')
                .then(response => response.json())
                .then(data => {
                    const statusDiv = document.getElementById('status');
                    if (data.connected) {
                        statusDiv.innerHTML = '<div class=\"status success\">Redroid connected: ' + data.device + '</div>';
                    } else {
                        statusDiv.innerHTML = '<div class=\"status error\">Redroid not connected</div>';
                    }
                });
        }
        
        function toggleAutoRefresh() {
            const button = event.target;
            if (autoRefreshInterval) {
                clearInterval(autoRefreshInterval);
                autoRefreshInterval = null;
                button.textContent = 'Start Auto Refresh';
                button.className = 'auto-refresh';
            } else {
                autoRefreshInterval = setInterval(takeScreenshot, 2000);
                button.textContent = 'Stop Auto Refresh';
                button.className = 'secondary';
            }
        }
        
        // Auto-refresh status
        refreshStatus();
        setInterval(refreshStatus, 10000);
    </script>
</body>
</html>
\"\"\"

@app.route('/')
def index():
    return render_template_string(HTML_TEMPLATE)

@app.route('/status')
def status():
    try:
        result = subprocess.run(['adb', 'devices'], capture_output=True, text=True, timeout=10)
        devices = result.stdout.strip().split('\n')[1:]
        connected = any('device' in device for device in devices if device.strip())
        device_info = devices[0] if devices else 'No device'
        return {'connected': connected, 'device': device_info}
    except:
        return {'connected': False, 'device': 'Error checking status'}

@app.route('/screenshot')
def screenshot():
    try:
        # Take screenshot using ADB
        subprocess.run(['adb', 'shell', 'screencap', '-p', '/sdcard/screenshot.png'], timeout=10)
        subprocess.run(['adb', 'pull', '/sdcard/screenshot.png', '/tmp/screenshot.png'], timeout=10)
        
        # Read and return the image
        with open('/tmp/screenshot.png', 'rb') as f:
            image_data = f.read()
        
        return Response(image_data, mimetype='image/png')
    except Exception as e:
        return str(e), 500

if __name__ == '__main__':
    # Wait for Redroid to be ready
    time.sleep(30)
    
    # Start ADB server and connect to Redroid
    subprocess.run(['adb', 'start-server'])
    subprocess.run(['adb', 'connect', 'android-redroid:5555'])
    
    app.run(host='0.0.0.0', port=6080, debug=False)
      ' > /app/app.py &&
        python3 /app/app.py
      "

volumes:
  redroid_data:

networks:
  redroid-network:
    driver: bridge 